name: CI

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  change-detection:
    name: 🔍 Change
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-change-detection.yml@e7f84f39ce2d3b6c5d1d04526b8f94f98e455143 # v2.2.0
    with:
      additional-cd-files: |
        spank/**
        .github/workflows/spank-tests.yml

  cpp-tests-ubuntu:
    name: 🇨 Test 🐧
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests)
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, ubuntu-24.04-arm]
        config: [Release]
        iqm-qc-alias: ["emerald:mock"]
        include:
          - runs-on: ubuntu-24.04
            config: Debug
            iqm-qc-alias: "emerald:mock"
          - runs-on: ubuntu-24.04
            config: Release
            iqm-qc-alias: "garnet:mock"
    uses: ./.github/workflows/cpp-tests-ubuntu.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      config: ${{ matrix.config }}
      iqm-qc-alias: ${{ matrix.iqm-qc-alias }}
    secrets:
      IQM_TOKEN: ${{ secrets.RESONANCE_API_KEY }}

  cpp-tests-macos:
    name: 🇨 Test 🍎
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests)
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-26-intel, macos-26]
        config: [Release]
        iqm-qc-alias: ["emerald:mock"]
        include:
          - runs-on: macos-26
            config: Debug
            iqm-qc-alias: "emerald:mock"
    uses: ./.github/workflows/cpp-tests-macos.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      config: ${{ matrix.config }}
      iqm-qc-alias: ${{ matrix.iqm-qc-alias }}
    secrets:
      IQM_TOKEN: ${{ secrets.RESONANCE_API_KEY }}

  cpp-tests-windows:
    name: 🇨 Test 🏁
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests)
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-2025, windows-11-arm]
        config: [Release]
        iqm-qc-alias: ["emerald:mock"]
        include:
          - runs-on: windows-2025
            config: Debug
            iqm-qc-alias: "emerald:mock"
    uses: ./.github/workflows/cpp-tests-windows.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      config: ${{ matrix.config }}
      iqm-qc-alias: ${{ matrix.iqm-qc-alias }}
    secrets:
      IQM_TOKEN: ${{ secrets.RESONANCE_API_KEY }}

  cpp-install-tests:
    name: 📦 Install
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests)
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-24.04, macos-26, windows-2025]
    uses: ./.github/workflows/cpp-install-tests.yml
    with:
      runs-on: ${{ matrix.runs-on }}
    secrets:
      IQM_TOKEN: ${{ secrets.RESONANCE_API_KEY }}

  cpp-coverage:
    name: 🇨 Coverage
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests)
    uses: ./.github/workflows/cpp-coverage.yml
    permissions:
      contents: read
      id-token: write
    secrets:
      IQM_TOKEN: ${{ secrets.RESONANCE_API_KEY }}

  cpp-linter:
    name: 🇨 Lint
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-linter)
    uses: ./.github/workflows/cpp-linter.yml
    with:
      clang-version: 22
      files-changed-only: true
      cpp-linter-extra-args: "-std=c++20"
    permissions:
      contents: read
      pull-requests: write # required to post comments on PRs

  python-linter:
    name: 🐍 Lint
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-tests)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-linter.yml@e7f84f39ce2d3b6c5d1d04526b8f94f98e455143 # v2.2.0
    with:
      check-stubs: false
      enable-ty: true
      enable-mypy: false

  examples:
    name: 🐍 End-to-End Examples
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-tests)
    uses: ./.github/workflows/python-examples.yml

  build-sdist:
    name: 🚀 CD
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-tests) || fromJSON(needs.change-detection.outputs.run-cd)
    uses: ./.github/workflows/python-packaging-sdist.yml

  build-wheel:
    name: 🚀 CD
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-tests) || fromJSON(needs.change-detection.outputs.run-cd)
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          [
            ubuntu-24.04,
            ubuntu-24.04-arm,
            macos-26-intel,
            macos-26,
            windows-2025,
            windows-11-arm,
          ]
    uses: ./.github/workflows/python-packaging-cibuildwheel.yml
    with:
      runs-on: ${{ matrix.runs-on }}
    secrets:
      IQM_TOKEN: ${{ secrets.RESONANCE_API_KEY }}

  spank-tests:
    name: 🇸 Test SPANK
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests) || fromJSON(needs.change-detection.outputs.run-cd)
    uses: ./.github/workflows/spank-tests.yml
    secrets:
      IQM_TOKEN: ${{ secrets.RESONANCE_API_KEY }}

  # this job does nothing and is only used for branch protection
  required-checks-pass:
    name: 🚦 Check
    if: always()
    needs:
      - change-detection
      - cpp-tests-ubuntu
      - cpp-tests-macos
      - cpp-tests-windows
      - cpp-install-tests
      - cpp-coverage
      - cpp-linter
      - python-linter
      - examples
      - build-sdist
      - build-wheel
      - spank-tests
    runs-on: ubuntu-slim
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          allowed-skips: >-
            ${{
              fromJSON(needs.change-detection.outputs.run-cpp-tests)
              && '' || 'cpp-tests-ubuntu,cpp-tests-macos,cpp-tests-windows,cpp-install-tests,cpp-coverage,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-cpp-linter)
              && '' || 'cpp-linter,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-python-tests)
              && '' || 'python-linter,examples,'
            }}
            ${{
              (fromJSON(needs.change-detection.outputs.run-python-tests) || fromJSON(needs.change-detection.outputs.run-cd))
              && '' || 'build-sdist,'
            }}
            ${{
              (fromJSON(needs.change-detection.outputs.run-cpp-tests) || fromJSON(needs.change-detection.outputs.run-cd))
              && '' || 'spank-tests,'
            }}
            ${{
              (fromJSON(needs.change-detection.outputs.run-python-tests) || fromJSON(needs.change-detection.outputs.run-cd))
              && '' || 'build-wheel,'
            }}
          jobs: ${{ toJSON(needs) }}
