name: 🇨 • Tests • macos
on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The macOS runner image to use. Defaults to 'macos-latest'.
          This can be any valid macOS runner image, such as 'macos-13', 'macos-14', or 'macos-15'.
        default: "macos-latest"
        type: string
      config:
        description: >
          The build type to use. Defaults to 'Release'.
          This can be any valid CMake build type, such as 'Debug' or 'Release'.
        default: "Release"
        type: string
      iqm-qc-alias:
        description: >
          The alias of the IQM quantum computer to use for testing. Defaults to 'emerald:mock'.
          This can be any valid IQM quantum computer alias.
        default: "emerald:mock"
        type: string
    secrets:
      IQM_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  cpp-tests-macos:
    name: 🍎 ${{ inputs.runs-on }} ${{ inputs.config }} ${{ inputs.iqm-qc-alias }}
    runs-on: ${{ inputs.runs-on }}
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
      CTEST_PARALLEL_LEVEL: 4
      FORCE_COLOR: 3
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      # Set up ccache for faster C++ builds
      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@802ec72ba1d54bbf75c52f45367253d6abec30f5 # v1.5.8
        with:
          prepend_symlinks_to_path: false
          override_cache_key: c++-tests-${{ inputs.runs-on }}-${{ inputs.config }}
      - name: Configure CMake
        env:
          CONFIG: ${{ inputs.config }}
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE="$CONFIG"
      # build the project in the specified mode
      - name: Build
        run: cmake --build build
      # run the tests
      - name: Test
        env:
          IQM_BASE_URL: "https://resonance.iqm.tech"
          IQM_QC_ALIAS: ${{ inputs.iqm-qc-alias }}
          IQM_TOKEN: ${{ secrets.IQM_TOKEN }}
          IQM_CPP_API_LOG_LEVEL: "DEBUG"
        run: ctest --output-on-failure --test-dir build --timeout 600 --repeat until-pass:3
