name: 🐍 • Packaging

on:
  workflow_call:
    inputs:
      runs-on:
        description: "The runner image to test on"
        default: "ubuntu-24.04"
        type: string
    secrets:
      IQM_TOKEN:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-python-packaging-cibw-${{ inputs.runs-on }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-wheel:
    name: 🎡 ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: ${{ !startsWith(inputs.runs-on, 'ubuntu') }}
          save-cache: ${{ github.ref == 'refs/heads/main' }}

      # run cibuildwheel to build wheels for the specified Python version
      - uses: pypa/cibuildwheel@294735312765b09d24a2fbec22660ce817587d55 # v4.1.0
        env:
          IQM_BASE_URL: "https://resonance.iqm.tech"
          IQM_QC_ALIAS: "emerald:mock"
          IQM_TOKEN: ${{ secrets.IQM_TOKEN }}
          IQM_CPP_API_LOG_LEVEL: "DEBUG"

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      # upload the wheels as an artifact (adds a `dev-` prefix for PRs)
      - name: Upload wheels
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ github.event_name == 'pull_request' && 'dev-' || '' }}cibw-wheels-${{ inputs.runs-on }}
          path: wheelhouse/*.whl
